/**
 * Academic Word List (AWL) curated across sublists 1-10
 * and Academic Transitional Devices for IELTS Writing Assessment.
 */

export const ACADEMIC_WORD_LIST: Record<
  string,
  { sublist: number; cefr: string; definition: string; definitionVi: string }
> = {
  // Sublist 1 (Most frequent academic words)
  analyze: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Examine methodically and in detail',
    definitionVi: 'Phân tích chi tiết',
  },
  analysis: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Detailed examination of elements or structure',
    definitionVi: 'Sự phân tích',
  },
  approach: {
    sublist: 1,
    cefr: 'B2',
    definition: 'A way of dealing with something',
    definitionVi: 'Phương pháp tiếp cận',
  },
  area: { sublist: 1, cefr: 'B1', definition: 'A subject or range of activity', definitionVi: 'Lĩnh vực, khu vực' },
  assess: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Evaluate or estimate the ability, value, or quality',
    definitionVi: 'Đánh giá',
  },
  assessment: {
    sublist: 1,
    cefr: 'B2',
    definition: 'The evaluation or estimation of the nature or quality',
    definitionVi: 'Sự đánh giá',
  },
  assume: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Suppose to be the case, without proof',
    definitionVi: 'Giả định, cho rằng',
  },
  authority: {
    sublist: 1,
    cefr: 'B2',
    definition: 'The power or right to give orders or make decisions',
    definitionVi: 'Thẩm quyền, chuyên gia',
  },
  available: { sublist: 1, cefr: 'B1', definition: 'Able to be used or obtained', definitionVi: 'Có sẵn, hiện có' },
  benefit: {
    sublist: 1,
    cefr: 'B1',
    definition: 'An advantage or profit gained from something',
    definitionVi: 'Lợi ích',
  },
  concept: { sublist: 1, cefr: 'B2', definition: 'An abstract idea or general notion', definitionVi: 'Khái niệm' },
  consist: { sublist: 1, cefr: 'B1', definition: 'Be composed or made up of', definitionVi: 'Bao gồm' },
  constitute: {
    sublist: 1,
    cefr: 'C1',
    definition: 'Be a part of a whole; establish',
    definitionVi: 'Cấu thành, tạo nên',
  },
  context: {
    sublist: 1,
    cefr: 'B2',
    definition: 'The circumstances that form the setting for an event',
    definitionVi: 'Bối cảnh',
  },
  contract: {
    sublist: 1,
    cefr: 'B1',
    definition: 'A written or spoken agreement',
    definitionVi: 'Hợp đồng, sự thu nhỏ',
  },
  create: { sublist: 1, cefr: 'A2', definition: 'Bring something into existence', definitionVi: 'Tạo ra, sáng tạo' },
  data: {
    sublist: 1,
    cefr: 'B1',
    definition: 'Facts and statistics collected together for analysis',
    definitionVi: 'Dữ liệu',
  },
  define: {
    sublist: 1,
    cefr: 'B1',
    definition: 'State or describe exactly the nature or scope',
    definitionVi: 'Định nghĩa',
  },
  derive: {
    sublist: 1,
    cefr: 'C1',
    definition: 'Obtain something from a specified source',
    definitionVi: 'Bắt nguồn từ',
  },
  distribute: { sublist: 1, cefr: 'B2', definition: 'Give shares of something; deal out', definitionVi: 'Phân phối' },
  economy: {
    sublist: 1,
    cefr: 'B1',
    definition: 'The state of a country or region in terms of production',
    definitionVi: 'Nền kinh tế',
  },
  environment: {
    sublist: 1,
    cefr: 'B1',
    definition: 'The surroundings or conditions in which an organism operates',
    definitionVi: 'Môi trường',
  },
  establish: { sublist: 1, cefr: 'B2', definition: 'Set up on a firm or permanent basis', definitionVi: 'Thiết lập' },
  estimate: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Roughly calculate or judge the value or quantity',
    definitionVi: 'Ước tính',
  },
  evidence: {
    sublist: 1,
    cefr: 'B2',
    definition: 'The available body of facts indicating whether a belief is true',
    definitionVi: 'Bằng chứng',
  },
  factor: {
    sublist: 1,
    cefr: 'B2',
    definition: 'A circumstance, fact, or influence that contributes to a result',
    definitionVi: 'Yếu tố',
  },
  finance: {
    sublist: 1,
    cefr: 'B2',
    definition: 'The management of large amounts of money',
    definitionVi: 'Tài chính',
  },
  formula: {
    sublist: 1,
    cefr: 'B2',
    definition: 'A mathematical relationship or rule expressed in symbols',
    definitionVi: 'Công thức',
  },
  function: {
    sublist: 1,
    cefr: 'B2',
    definition: 'An activity or purpose natural to or intended for a person or thing',
    definitionVi: 'Chức năng',
  },
  identify: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Establish or indicate who or what someone or something is',
    definitionVi: 'Nhận diện, xác định',
  },
  indicate: { sublist: 1, cefr: 'B2', definition: 'Point out; show', definitionVi: 'Chỉ ra' },
  individual: { sublist: 1, cefr: 'B1', definition: 'Single; separate', definitionVi: 'Cá nhân' },
  interpret: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Explain the meaning of information, words, or actions',
    definitionVi: 'Diễn giải, thông dịch',
  },
  involve: {
    sublist: 1,
    cefr: 'B1',
    definition: 'Have or include as a necessary part or result',
    definitionVi: 'Liên quan, bao gồm',
  },
  issue: {
    sublist: 1,
    cefr: 'B1',
    definition: 'An important topic or problem for debate or discussion',
    definitionVi: 'Vấn đề',
  },
  labor: { sublist: 1, cefr: 'B2', definition: 'Work, especially hard physical work', definitionVi: 'Lao động' },
  legal: { sublist: 1, cefr: 'B1', definition: 'Permitted by or based on law', definitionVi: 'Hợp pháp' },
  major: { sublist: 1, cefr: 'B1', definition: 'Important, serious, or significant', definitionVi: 'Chính, chủ yếu' },
  method: {
    sublist: 1,
    cefr: 'B1',
    definition: 'A particular form of procedure for accomplishing or approaching something',
    definitionVi: 'Phương pháp',
  },
  occur: { sublist: 1, cefr: 'B2', definition: 'Happen; take place', definitionVi: 'Xảy ra' },
  percent: { sublist: 1, cefr: 'A2', definition: 'One part in every hundred', definitionVi: 'Phần trăm' },
  period: { sublist: 1, cefr: 'B1', definition: 'A length or portion of time', definitionVi: 'Giai đoạn, thời kỳ' },
  policy: {
    sublist: 1,
    cefr: 'B1',
    definition: 'A course or principle of action adopted or proposed by a government or party',
    definitionVi: 'Chính sách',
  },
  principle: {
    sublist: 1,
    cefr: 'B2',
    definition: 'A fundamental truth or proposition that serves as the foundation',
    definitionVi: 'Nguyên tắc',
  },
  procedure: {
    sublist: 1,
    cefr: 'B2',
    definition: 'An established or official way of doing something',
    definitionVi: 'Quy trình, thủ tục',
  },
  process: {
    sublist: 1,
    cefr: 'B1',
    definition: 'A series of actions or steps taken in order to achieve a particular end',
    definitionVi: 'Tiến trình, quá trình',
  },
  require: { sublist: 1, cefr: 'B1', definition: 'Need for a particular purpose', definitionVi: 'Yêu cầu, đòi hỏi' },
  research: {
    sublist: 1,
    cefr: 'B1',
    definition: 'The systematic investigation into and study of materials and sources',
    definitionVi: 'Nghiên cứu',
  },
  respond: { sublist: 1, cefr: 'B1', definition: 'Say something in reply', definitionVi: 'Phản hồi, đáp lại' },
  role: {
    sublist: 1,
    cefr: 'B1',
    definition: 'The function assumed or part played by a person or thing in a particular situation',
    definitionVi: 'Vai trò',
  },
  section: {
    sublist: 1,
    cefr: 'B1',
    definition: 'Any of the more or less distinct parts into which something is divided',
    definitionVi: 'Phần, mục',
  },
  sector: {
    sublist: 1,
    cefr: 'B2',
    definition: 'An area or portion that is distinct from others',
    definitionVi: 'Khu vực, ngành',
  },
  significant: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Sufficiently great or important to be worthy of attention',
    definitionVi: 'Đáng kể, quan trọng',
  },
  similar: { sublist: 1, cefr: 'B1', definition: 'Resembling without being identical', definitionVi: 'Tương tự' },
  source: {
    sublist: 1,
    cefr: 'B1',
    definition: 'A place, person, or thing from which something comes or can be obtained',
    definitionVi: 'Nguồn',
  },
  specific: { sublist: 1, cefr: 'B1', definition: 'Clearly defined or identified', definitionVi: 'Cụ thể' },
  structure: {
    sublist: 1,
    cefr: 'B2',
    definition: 'The arrangement of and relations between the parts or elements of something complex',
    definitionVi: 'Cấu trúc',
  },
  theory: {
    sublist: 1,
    cefr: 'B2',
    definition: 'A supposition or a system of ideas intended to explain something',
    definitionVi: 'Lý thuyết',
  },
  vary: {
    sublist: 1,
    cefr: 'B2',
    definition: 'Differ in size, amount, degree, or nature from something else of the same general class',
    definitionVi: 'Biến đổi, thay đổi',
  },

  // Sublist 2-5 (Band 7.5 - 8.5 Academic Vocabulary)
  achieve: {
    sublist: 2,
    cefr: 'B1',
    definition: 'Successfully bring about or reach by effort',
    definitionVi: 'Đạt được',
  },
  acquire: { sublist: 2, cefr: 'B2', definition: 'Buy or obtain for oneself', definitionVi: 'Thu nhận, đạt được' },
  adequate: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Satisfactory or acceptable in quality or quantity',
    definitionVi: 'Đầy đủ, thỏa đáng',
  },
  allocate: { sublist: 2, cefr: 'C1', definition: 'Distribute for a particular purpose', definitionVi: 'Phân bổ' },
  alternative: {
    sublist: 2,
    cefr: 'B2',
    definition: 'One of two or more available possibilities',
    definitionVi: 'Thay thế, giải pháp khác',
  },
  appropriate: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Suitable or proper in the circumstances',
    definitionVi: 'Thích hợp',
  },
  aspect: {
    sublist: 2,
    cefr: 'B2',
    definition: 'A particular part or feature of something',
    definitionVi: 'Khía cạnh',
  },
  complex: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Consisting of many different and connected parts',
    definitionVi: 'Phức tạp',
  },
  consequence: {
    sublist: 2,
    cefr: 'B2',
    definition: 'A result or effect of an action or condition',
    definitionVi: 'Hậu quả, hệ quả',
  },
  construct: { sublist: 2, cefr: 'B2', definition: 'Build or erect something', definitionVi: 'Xây dựng' },
  distinct: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Recognizably different in nature from something else',
    definitionVi: 'Khác biệt, rõ rệt',
  },
  element: {
    sublist: 2,
    cefr: 'B2',
    definition: 'An essential or characteristic part of something abstract',
    definitionVi: 'Yếu tố, thành phần',
  },
  evaluate: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Form an idea of the amount, number, or value of',
    definitionVi: 'Đánh giá',
  },
  feature: {
    sublist: 2,
    cefr: 'B1',
    definition: 'A distinctive attribute or aspect of something',
    definitionVi: 'Đặc điểm',
  },
  impact: { sublist: 2, cefr: 'B2', definition: 'A marked effect or influence', definitionVi: 'Tác động, ảnh hưởng' },
  maintain: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Cause or enable a condition or state of affairs to continue',
    definitionVi: 'Duy trì',
  },
  obtain: { sublist: 2, cefr: 'B2', definition: 'Get, acquire, or secure', definitionVi: 'Đạt được, lấy được' },
  potential: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Having or showing the capacity to develop into something in the future',
    definitionVi: 'Tiềm năng',
  },
  previous: {
    sublist: 2,
    cefr: 'B1',
    definition: 'Existing or occurring before in time or order',
    definitionVi: 'Trước đó',
  },
  primary: { sublist: 2, cefr: 'B2', definition: 'Of chief importance; principal', definitionVi: 'Chủ yếu, cơ bản' },
  regulate: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Control or maintain the rate or speed of a machine or process',
    definitionVi: 'Điều tiết, quy định',
  },
  relevant: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Closely connected or appropriate to what is being done or considered',
    definitionVi: 'Liên quan, thích hợp',
  },
  restrict: { sublist: 2, cefr: 'B2', definition: 'Put a limit on; keep under control', definitionVi: 'Hạn chế' },
  secure: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Fixed or fastened so as not to give way, become loose, or be lost',
    definitionVi: 'Đảm bảo, an toàn',
  },
  seek: { sublist: 2, cefr: 'B2', definition: 'Attempt to find or obtain', definitionVi: 'Tìm kiếm' },
  site: {
    sublist: 2,
    cefr: 'B1',
    definition: 'An area of ground on which a town, building, or monument is being constructed',
    definitionVi: 'Địa điểm',
  },
  strategy: {
    sublist: 2,
    cefr: 'B2',
    definition: 'A plan of action designed to achieve a long-term or overall aim',
    definitionVi: 'Chiến lược',
  },
  survey: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Investigate the opinions or experience of a group of people',
    definitionVi: 'Khảo sát',
  },
  transfer: {
    sublist: 2,
    cefr: 'B2',
    definition: 'Move from one place, person, or position to another',
    definitionVi: 'Chuyển giao',
  },

  // Band 8-9 Advanced Vocabulary
  comprehensive: {
    sublist: 3,
    cefr: 'C1',
    definition: 'Complete; including all or nearly all elements or aspects',
    definitionVi: 'Toàn diện',
  },
  paradigm: {
    sublist: 7,
    cefr: 'C2',
    definition: 'A typical example or pattern of something; a model',
    definitionVi: 'Mô hình, kiểu mẫu',
  },
  predominantly: { sublist: 8, cefr: 'C1', definition: 'Mainly; for the most part', definitionVi: 'Phần lớn, chủ yếu' },
  ubiquitous: {
    sublist: 9,
    cefr: 'C2',
    definition: 'Present, appearing, or found everywhere',
    definitionVi: 'Phổ biến khắp nơi',
  },
  mitigate: {
    sublist: 9,
    cefr: 'C1',
    definition: 'Make less severe, serious, or painful',
    definitionVi: 'Giảm nhẹ, xoa dịu',
  },
  exacerbate: {
    sublist: 10,
    cefr: 'C2',
    definition: 'Make a problem, bad situation, or negative feeling worse',
    definitionVi: 'Làm trầm trọng thêm',
  },
  proliferation: {
    sublist: 9,
    cefr: 'C2',
    definition: 'Rapid increase in the number or amount of something',
    definitionVi: 'Sự tăng sinh nhanh chóng',
  },
  detrimental: { sublist: 8, cefr: 'C1', definition: 'Tending to cause harm', definitionVi: 'Có hại, bất lợi' },
  unprecedented: {
    sublist: 7,
    cefr: 'C2',
    definition: 'Never done or known before',
    definitionVi: 'Chưa từng có tiền lệ',
  },
  imperative: {
    sublist: 8,
    cefr: 'C1',
    definition: 'Of vital importance; crucial',
    definitionVi: 'Cấp bách, thiết yếu',
  },
  facilitate: {
    sublist: 5,
    cefr: 'C1',
    definition: 'Make an action or process easy or easier',
    definitionVi: 'Tạo điều kiện thuận lợi',
  },
  counterpart: {
    sublist: 6,
    cefr: 'C1',
    definition: 'A person or thing corresponding to another',
    definitionVi: 'Bên tương ứng',
  },
  inevitable: {
    sublist: 8,
    cefr: 'B2',
    definition: 'Certain to happen; unavoidable',
    definitionVi: 'Không thể tránh khỏi',
  },
  paramount: {
    sublist: 9,
    cefr: 'C2',
    definition: 'More important than anything else; supreme',
    definitionVi: 'Tối quan trọng',
  },
  substantiate: {
    sublist: 9,
    cefr: 'C2',
    definition: 'Provide evidence to support or prove the truth of',
    definitionVi: 'Chứng minh, minh chứng',
  },
  discernible: {
    sublist: 9,
    cefr: 'C2',
    definition: 'Able to be discerned; perceptible',
    definitionVi: 'Có thể nhận thức rõ',
  },
  diminish: { sublist: 9, cefr: 'B2', definition: 'Make or become less', definitionVi: 'Thu nhỏ, giảm sút' },
  advocate: { sublist: 7, cefr: 'B2', definition: 'Publicly recommend or support', definitionVi: 'Ủng hộ, tán thành' },
};

/**
 * Cohesive Discourse Markers categorized by IELTS rhetorical function
 */
export const DISCOURSE_TRANSITIONS = {
  addition: [
    'furthermore',
    'moreover',
    'in addition',
    'additionally',
    'not only',
    'besides',
    'likewise',
    'equally important',
    'what is more',
  ],
  contrast: [
    'however',
    'nevertheless',
    'nonetheless',
    'on the contrary',
    'in contrast',
    'on the other hand',
    'conversely',
    'despite',
    'in spite of',
    'whereas',
    'while',
    'although',
    'even though',
  ],
  cause_effect: [
    'consequently',
    'as a result',
    'therefore',
    'thus',
    'hence',
    'accordingly',
    'owing to',
    'due to',
    'leads to',
    'results in',
    'for this reason',
  ],
  exemplification: [
    'for example',
    'for instance',
    'to illustrate',
    'such as',
    'namely',
    'a prime example of this is',
    'specifically',
    'to give a clear example',
  ],
  conclusion: [
    'in conclusion',
    'to conclude',
    'to summarize',
    'in summary',
    'in a nutshell',
    'taking everything into account',
    'all things considered',
    'to sum up',
  ],
  opinion_emphasis: [
    'it is undeniable that',
    'it is widely believed that',
    'it is evident that',
    'from my perspective',
    'in my view',
    'i firmly believe',
    'it is worth noting that',
  ],
};

export const COMMON_COLLOCATIONS = [
  'play a vital role',
  'play an essential role',
  'pose a threat to',
  'shed light on',
  'take into consideration',
  'take into account',
  'bridge the gap',
  'reap the benefits',
  'pave the way for',
  'address the issue',
  'tackle the problem',
  'raise awareness',
  'have a profound impact',
  'exert a negative effect',
  'reach a consensus',
  'make a concerted effort',
  'strike a balance',
  'foster economic growth',
  'broaden their horizons',
  'gain a competitive edge',
];
