import type { Language, Skill } from "../lib/model";

const en = {
  today: "Today",
  practice: "Practice",
  review: "Review",
  library: "Library",
  settings: "Settings",
  greeting: "Your next focused step",
  private: "Private by design",
  noLogin: "No account. No cloud. Just practice.",
  goal: "Daily focus",
  minutes: "min",
  streak: "day streak",
  due: "due now",
  startReview: "Review due cards",
  quickPractice: "Skill circuit",
  quickHint: "Short, active drills across all four IELTS skills.",
  capture: "Capture from page",
  captureHint:
    "Select useful English on the current page, then capture it as a review card.",
  captured: "Selection captured",
  noSelection: "Select some text on the page first.",
  back: "Meaning or note",
  context: "Context",
  saveCard: "Save card",
  listening: "Listening",
  reading: "Reading",
  writing: "Writing",
  speaking: "Speaking",
  listenPrompt: "Listen once, then type what you heard.",
  play: "Play prompt",
  check: "Check answer",
  answer: "Your transcript",
  readingPrompt: "Read for the writer’s main claim, not isolated keywords.",
  submit: "Submit",
  writingPrompt:
    "Write a concise position and support it with one specific reason.",
  wordCount: "words",
  complete: "Complete drill",
  speakingPrompt:
    "Shadow the model sentence: listen, record, compare, then self-rate.",
  record: "Start recording",
  stop: "Stop recording",
  compare: "Play recording",
  selfRate: "How closely did your rhythm and stress match?",
  again: "Again",
  hard: "Hard",
  good: "Good",
  easy: "Easy",
  reveal: "Reveal answer",
  source: "Source",
  emptyReview: "You are caught up",
  emptyReviewHint: "Capture a phrase from any page or continue a skill drill.",
  cards: "cards",
  export: "Export backup",
  import: "Import backup",
  language: "Language",
  dailyGoal: "Daily goal",
  targetBand: "Target band",
  examDate: "Exam date",
  dataPrivacy: "Data & privacy",
  privacyBody:
    "All study data stays in Firefox storage. No analytics, account, ads, AI API, or remote server.",
  deleteAll: "Delete all local data",
  confirmDelete: "Click again to permanently delete local data",
  saved: "Saved",
  accuracy: "word accuracy",
  correct: "Correct",
  tryAgain: "Not quite — inspect the claim and try again.",
  libraryEmpty: "Your phrase library is empty.",
  openSource: "Open source & evidence-informed",
  citations: "Research notes",
  goalReached: "Goal reached — excellent deliberate practice.",
};

const vi: typeof en = {
  today: "Hôm nay",
  practice: "Luyện tập",
  review: "Ôn tập",
  library: "Thư viện",
  settings: "Cài đặt",
  greeting: "Bước tập trung tiếp theo",
  private: "Riêng tư từ thiết kế",
  noLogin: "Không tài khoản. Không đám mây. Chỉ luyện tập.",
  goal: "Mục tiêu hôm nay",
  minutes: "phút",
  streak: "ngày liên tiếp",
  due: "cần ôn",
  startReview: "Ôn thẻ đến hạn",
  quickPractice: "Vòng luyện kỹ năng",
  quickHint: "Bài tập ngắn, chủ động cho đủ bốn kỹ năng IELTS.",
  capture: "Lưu từ trang web",
  captureHint:
    "Chọn đoạn tiếng Anh trên trang hiện tại rồi lưu thành thẻ ôn tập.",
  captured: "Đã lấy đoạn chọn",
  noSelection: "Hãy chọn một đoạn văn trên trang trước.",
  back: "Nghĩa hoặc ghi chú",
  context: "Ngữ cảnh",
  saveCard: "Lưu thẻ",
  listening: "Nghe",
  reading: "Đọc",
  writing: "Viết",
  speaking: "Nói",
  listenPrompt: "Nghe một lần rồi gõ lại nội dung.",
  play: "Phát câu mẫu",
  check: "Kiểm tra",
  answer: "Nội dung bạn nghe",
  readingPrompt: "Đọc để tìm luận điểm chính, không chỉ dò từ khóa.",
  submit: "Nộp",
  writingPrompt: "Viết quan điểm ngắn gọn và hỗ trợ bằng một lý do cụ thể.",
  wordCount: "từ",
  complete: "Hoàn thành",
  speakingPrompt: "Nói đuổi câu mẫu: nghe, ghi âm, so sánh rồi tự đánh giá.",
  record: "Bắt đầu ghi âm",
  stop: "Dừng ghi âm",
  compare: "Nghe bản ghi",
  selfRate: "Nhịp điệu và trọng âm của bạn giống câu mẫu đến đâu?",
  again: "Lại",
  hard: "Khó",
  good: "Tốt",
  easy: "Dễ",
  reveal: "Hiện đáp án",
  source: "Nguồn",
  emptyReview: "Bạn đã ôn xong",
  emptyReviewHint: "Lưu một cụm từ từ trang web hoặc tiếp tục luyện kỹ năng.",
  cards: "thẻ",
  export: "Xuất bản sao",
  import: "Nhập bản sao",
  language: "Ngôn ngữ",
  dailyGoal: "Mục tiêu hằng ngày",
  targetBand: "Band mục tiêu",
  examDate: "Ngày thi",
  dataPrivacy: "Dữ liệu & riêng tư",
  privacyBody:
    "Toàn bộ dữ liệu nằm trong Firefox. Không phân tích, tài khoản, quảng cáo, API AI hay máy chủ từ xa.",
  deleteAll: "Xóa toàn bộ dữ liệu",
  confirmDelete: "Bấm lần nữa để xóa vĩnh viễn dữ liệu cục bộ",
  saved: "Đã lưu",
  accuracy: "độ chính xác từ",
  correct: "Chính xác",
  tryAgain: "Chưa đúng — hãy xem luận điểm và thử lại.",
  libraryEmpty: "Thư viện cụm từ đang trống.",
  openSource: "Mã nguồn mở & dựa trên bằng chứng",
  citations: "Ghi chú nghiên cứu",
  goalReached: "Đạt mục tiêu — một buổi luyện tập có chủ đích tuyệt vời.",
};

export type Copy = typeof en;
export const getCopy = (language: Language): Copy =>
  language === "vi" ? vi : en;
export const skillLabel = (copy: Copy, skill: Skill): string => copy[skill];

export const LISTENING_SENTENCE =
  "The proposal was postponed because the evidence remained inconclusive.";
export const SPEAKING_SENTENCE =
  "Public transport can reduce congestion while improving access to employment.";
export const READING_PASSAGE =
  "Urban trees do more than beautify streets. By shading buildings and releasing water vapour, they can reduce local temperatures. Their benefits are greatest when cities choose species suited to local conditions and maintain them over time.";
export const READING_OPTIONS = [
  "Trees are mainly valuable because they make streets attractive.",
  "Well-chosen and maintained urban trees can cool cities.",
  "Every tree species provides identical benefits in all cities.",
];
export const WRITING_PROMPT =
  "Some people believe cities should spend more on public transport than on roads. To what extent do you agree or disagree?";
