import { describe, expect, it } from 'vitest';
import {
  createVideoPracticeSession,
  createVocabularyFromQuestion,
  getPracticeProgress,
  getTranscriptStats,
  normalizeAnswer,
  parseTimestamp,
  parseTranscript,
  stripCueMarkup,
  validateTranscriptInput,
  verifyAnswer,
} from '../../src/video/transcriptPractice';

describe('transcriptPractice', () => {
  const academicTranscript = [
    'The analysis of coastal ecosystems provides significant evidence for climate policy.',
    'Researchers assess environmental data to identify practical solutions for communities.',
    'A sustainable approach can benefit learners and local authorities alike.',
  ].join(' ');

  it('parses timestamps and strips caption markup safely', () => {
    expect(parseTimestamp('01:02:03.500')).toBe(3723.5);
    expect(parseTimestamp('02:03,250')).toBe(123.25);
    expect(parseTimestamp('01:02')).toBe(62);
    expect(parseTimestamp('00:60')).toBeUndefined();
    expect(parseTimestamp('not-a-time')).toBeUndefined();
    expect(stripCueMarkup('<v Speaker>&amp; <i>Research</i></v> -->')).toBe('&amp; Research -->');
    expect(stripCueMarkup('2 > 1')).toBe('2 > 1');
    expect(stripCueMarkup('<i unfinished')).toBe('');
  });

  it('parses WebVTT/SRT cues, ignores metadata, and deduplicates repeated captions', () => {
    const parsed = parseTranscript(
      `WEBVTT - captions\n\nNOTE generated by a player\nignore this note\n\n1\n00:00:01.500 --> 00:00:03.000 align:start\n<i>Research</i> improves outcomes.\n\n2\n00:00:03,100 --> 00:00:05,000\nResearch improves outcomes.\n\n3\n00:00:05.200 --> 00:00:07.500\nAnalysis supports evidence.`,
    );

    expect(parsed).toEqual([
      {
        id: 'cue-1',
        startSeconds: 1.5,
        endSeconds: 3,
        text: 'Research improves outcomes.',
      },
      {
        id: 'cue-2',
        startSeconds: 5.2,
        endSeconds: 7.5,
        text: 'Analysis supports evidence.',
      },
    ]);
  });

  it('creates sentence cues from a plain transcript and rejects invalid source text', () => {
    const plain = parseTranscript('First idea is clear! Second idea asks why? Final thought remains.');
    expect(plain.map((cue) => cue.text)).toEqual([
      'First idea is clear!',
      'Second idea asks why?',
      'Final thought remains.',
    ]);
    expect(plain.every((cue) => cue.startSeconds === undefined)).toBe(true);

    expect(validateTranscriptInput('  ')).toBe('Add at least one sentence from a transcript.');
    expect(validateTranscriptInput('word '.repeat(12001))).toContain('60,000');
    expect(validateTranscriptInput('A useful transcript is ready.')).toBeUndefined();
  });

  it('creates deterministic, academic gap-fill practice and a bilingual vocabulary card', () => {
    const session = createVideoPracticeSession({
      title: 'Coastal science',
      sourceUrl: 'https://www.youtube.com/watch?v=example',
      transcript: academicTranscript,
      questionLimit: 3,
      createdAt: '2026-09-27T12:00:00.000Z',
    });

    expect(session).toMatchObject({
      title: 'Coastal science',
      sourceUrl: 'https://www.youtube.com/watch?v=example',
      createdAt: '2026-09-27T12:00:00.000Z',
      stats: {
        cueCount: 3,
        wordCount: 31,
        academicWordCount: expect.any(Number),
      },
    });
    expect(session.questions).toHaveLength(3);
    expect(session.questions.every((question) => question.clozeText.includes('_____'))).toBe(true);
    expect(
      session.questions.every((question) => !question.clozeText.toLowerCase().includes(question.answer.toLowerCase())),
    ).toBe(true);

    const academicQuestion = session.questions.find((question) => question.academicWord);
    expect(academicQuestion).toBeDefined();
    expect(createVocabularyFromQuestion(academicQuestion!)).toMatchObject({
      word: academicQuestion!.answer,
      definitionEn: expect.any(String),
      definitionVi: expect.any(String),
      isAWL: true,
    });
    expect(createVocabularyFromQuestion({ ...academicQuestion!, academicWord: undefined })).toBeUndefined();
    expect(
      createVocabularyFromQuestion({
        ...academicQuestion!,
        academicWord: { sublist: 4, definitionEn: 'A C1 word', definitionVi: 'Từ C1' },
      })?.cefrLevel,
    ).toBe('C1');
    expect(
      createVocabularyFromQuestion({
        ...academicQuestion!,
        academicWord: { sublist: 7, definitionEn: 'A C2 word', definitionVi: 'Từ C2' },
      }),
    ).toMatchObject({ cefrLevel: 'C2', bandScore: 8 });
  });

  it('keeps non-academic cloze choices usable and reports empty transcript stats', () => {
    const nonAcademicSession = createVideoPracticeSession({
      title: 'Odd vocabulary',
      transcript: 'Zyzzogeton xylography quizzically ambled.',
    });
    expect(nonAcademicSession.questions[0].academicWord).toBeUndefined();
    expect(getTranscriptStats('!!!')).toEqual({
      cueCount: 0,
      wordCount: 0,
      uniqueWordCount: 0,
      academicWordCount: 0,
      estimatedMinutes: 0,
    });
  });

  it('validates generated sessions and normalizes answers without leaking punctuation into grades', () => {
    expect(() => createVideoPracticeSession({ title: '', transcript: '   ' })).toThrow('Add at least one sentence');
    expect(createVideoPracticeSession({ title: ' ', transcript: 'Research improves outcomes.' }).title).toBe(
      'Untitled video transcript',
    );
    expect(() => createVideoPracticeSession({ title: 'Short', transcript: 'A an the.' })).toThrow(
      'enough usable vocabulary',
    );

    expect(normalizeAnswer('  Evidence’s, ')).toBe("evidence's");
    expect(verifyAnswer("Evidence's", 'evidence’s!')).toBe(true);
    expect(verifyAnswer('analysis', 'evidence')).toBe(false);
  });

  it('summarizes practice progress across answered, correct, and unanswered gaps', () => {
    const session = createVideoPracticeSession({ title: 'Progress', transcript: academicTranscript, questionLimit: 3 });
    const answers = {
      [session.questions[0].id]: session.questions[0].answer,
      [session.questions[1].id]: 'incorrect response',
    };

    expect(getPracticeProgress(session.questions, answers)).toEqual({
      answered: 2,
      correct: 1,
      total: 3,
      accuracyPercent: 50,
    });
    expect(getPracticeProgress([], {})).toEqual({
      answered: 0,
      correct: 0,
      total: 0,
      accuracyPercent: 0,
    });
  });
});
